### ISSUE TITLE
Set email field if user gave access to it

### ISSUE THREAD

**Issue by jhaoda** [SocialiteProviders/VKontakte#1]
VKontake send email only when receiving "access_token" if user grants permission.

Quick and dirty (maybe) solution:
````php
//vkontakte/src/provider.php

public function user()
{
    /** @type User $user */
    $user = parent::user();

    if (array_key_exists('email', $user->token)) {
        $user->map(['email' => $user->token['email']]);
    }

    return $user;
}
````

If this solution is ok, i can make PR.

**Comment by DraperStudio** [comment]
I just tested the login again and the $token object still only contains access_token, expires_in and user_id fields like the first time when I created the provider so there is no email field that could be checked for.

Also in the API documentation there is no mention about a way to retrieve the email address of an user.

**Comment by jhaoda** [comment]
Need to set scope like: `\Socialize::with('vkontakte')->scopes(['email'])->redirect();`

**Comment by DraperStudio** [comment]
Fix pushed https://github.com/SocialiteProviders/VKontakte/commit/93a0756e67ec90e85bee268edb275705f0b0cbd1 and v1.0.2 tagged
