### ISSUE TITLE
Change size photo and locale

### ISSUE THREAD

**Issue by Staruy** [SocialiteProviders/VKontakte#11]
please add in the ability to configure to set the size of the photo received and the language in which the answer comes
https://vk.com/dev/fields
https://vk.com/dev/api_requests

Provider.php line 39:
original:
$response = $this->getHttpClient()->get(
            'https://api.vk.com/method/users.get?user_ids='.$token['user_id'].'&fields=uid,first_name,last_name,screen_name,photo'
        );
example:
$response = $this->getHttpClient()->get(
            'https://api.vk.com/method/users.get?user_ids='.$token['user_id'].'&fields=uid,first_name,last_name,screen_name'.$PHOTO.$VKLANG
        );

**Comment by DraperStudio** [comment]
Send a PR.

**Comment by DraperStudio** [comment]
Closing, no PR so likely not really needed.
