### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by vsbeats** [SocialiteProviders/VKontakte#13]
After redirect i will get this error:

FatalErrorException in Provider.php line 91:
Call to undefined method SocialiteProviders\VKontakte\Provider::getAccessToken()

And in AbstractProvider this method does not exists realy

**Comment by DraperStudio** [comment]
Delete your vendor folder and run `composer install`.

**Comment by kambojaz** [comment]
Method getAccessToken() in Laravel\Socialite\Two\AbstractProvider is deprecated, now you should use getAccessTokenResponse()

**Comment by DraperStudio** [comment]
Will fix this within the next 24 hours for all providers.
--
Sent from myMail app for Android Friday, 03 June 2016, 07:44a.m. +02:00 from kambojaz  notifications@github.com :

**Comment by vsbeats** [comment]
Check my pull-request with fix https://github.com/SocialiteProviders/VKontakte/pull/14

**Comment by DraperStudio** [comment]
@vsbeats We will most likely fix this through the Manager package so that it takes effect for all providers.

**Comment by DraperStudio** [comment]
Try `composer update` to update to `v2.1.3` of the manager package. This change https://github.com/SocialiteProviders/Manager/commit/d92cdc628916b902d4d09cf09ac03ea0d3f74a15 should get the Providers working again for now.

**Comment by Butochnikov** [comment]
`composer updete` not helps.
We need to change the version.

**Comment by DraperStudio** [comment]
If it doesn't work please send a PR with a fix, none of us has test credentials for VKontakte.

**Comment by Butochnikov** [comment]
`composer clear-cache` not helps too.
just change the release version, please.

**Comment by AndyWendt** [comment]
Try deleting the `vendor/` directory and then run `composer update`.  We are not going to do a version bump unless we have an actual version to release.

**Comment by Butochnikov** [comment]
@AndyWendt of course I tried , did not help.

@DraperStudio now everything is fine. Thank you.

**Comment by StepanyanAlbert** [comment]
I am running into exact same problem I tried deleting vendor and composer update  and also  composer clear-cache  didn't work. Have you solved it??
