### ISSUE TITLE
Ability to manage fields

### ISSUE THREAD

**Issue by bstrx** [SocialiteProviders/VKontakte#15]
Hello!
What do you think about adding fields management like in Facebook Provider? I can do a PR for that.

**Comment by AndyWendt** [comment]
You can send a PR and we will take a look at it :smile:

**Comment by pi-kei** [comment]
Actually PR #5 did just that.

**Comment by bstrx** [comment]
@AndyWendt @pi-kei 
oh, looks like the same. I don't think that doing the same thing will lead to a different result)
It seems like I should just use my own provider and don't push those changes : (

**Comment by DraperStudio** [comment]
@bstrx You can send a PR for this and I will merge it.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/VKontakte/commit/d8c3dbb83c9b5d91351ec06ab19c0c85f05a1a75
