### ISSUE TITLE
Empty Email raise fatal error

### ISSUE THREAD

**Issue by h-zone** [SocialiteProviders/VKontakte#2]
If no email in VK account, login raise error

ClientException in RequestException.php line 89: Client error response [url] https://oauth.vk.com/access_token [status code] 401 [reason phrase] Unauthorized

See:
vkontakte/src/Provider.php:43

return array_merge($response, [
    'email' => $token['email'],
]);

I suggect to check for empty emails like this
return array_merge($response, [
    'email' => !empty($token['email']) ? $token['email'] : null,
]);

**Comment by DraperStudio** [comment]
Your Exception looks like the User denied permissions and/or you haven't received valid data from VKontakte.

Also `array_get($user, 'email')` is used so if there is no email it will just be set to null.
