### ISSUE TITLE
InvalidStateException not found

### ISSUE THREAD

**Issue by ju5tify** [SocialiteProviders/VKontakte#6]
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'SocialiteProviders\VKontakte\InvalidStateException' not found' in /var/www/***/vendor/socialiteproviders/vkontakte/src/Provider.php:86
Stack trace:
#0 {main}

**Comment by berpcor** [comment]
The problem is still exists. Could you please fix it?

**Comment by jhaoda** [comment]
Problem in https://github.com/SocialiteProviders/VKontakte/commit/de4d92dcafa818627e45f84f3b184a81e8b13693#diff-af3a35ce5c2351f8166a976f20e499a4R86
